# Generated by Django 6.0.2 on 2026-08-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_address_teacher_dob_teacher_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('Notes', 'Notes'), ('Assignment', 'Assignment'), ('Important Questions', 'Important Questions'), ('Practical', 'Practical'), ('PPT', 'PPT'), ('Syllabus', 'Syllabus'), ('Other', 'Other')], max_length=30)),
                ('course', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='study_materials/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
    ]
